### ISSUE TITLE
Binary operator

### ISSUE THREAD

**Issue by vvmgev** [makinhs/rest-api-tutorial#1]
if (user_permission_level & required_permission_level) {

**Comment by hht1230** [comment]
I had to swap in a regular compare instead of a bitwise AND for minimumPermissionLevelRequired to work correctly:
if (user_permission_level >= required_permission_level) { ... }

**Comment by makinhs** [comment]
Hi guys, thanks for reaching me out.

The approach that I've made is using bitwise AND. I reviewed the code and it is working as expected.

Let's say we have there 3 permissions:
FREE: 1
PAID: 4
PAID_PREMIUM: 8
ADMIN: 2048

And for user permission level we should have the same value or a sum of the values.
For example, a normal user who needs to have access to all free content + paid content should have at least a sum of 1 + 4 for it's own permission level. In this case, if the user will have a permission level = 5 it will pass all FREE and PAID permissions when using the & operator.

You can verify using the chrome console as:
let myPermissionLevel = 5;
myPermissionLevel & 1 -> 1 (true, for javascript if)
myPermissionLevel & 4 -> 4 (true, for javascript if)
myPermissionLevel & 8 -> 0 (false)

Most important there is that the level os permissions should be power of 2 (1, 2, 4, 8, 16, ...) and for the user permission level a sum of its permissions (such as 1+2, or 8+16, or 1+2+4+8+16)

**Comment by hht1230** [comment]
Marcos - Many thanks for posting the tutorial and github repo.  It's been really useful to understand how to set up a node REST api with permission levels and jwt and I appreciate you taking the time to do that.

I see how the bitwise AND can be used for checking for a match (on individual bits), but not how it can be used for checking if a level is equal to or above some specified level.  

Specifically, for this code in https://raw.githubusercontent.com/makinhs/rest-api-tutorial/master/common/middlewares/auth.permission.middleware.js

exports.minimumPermissionLevelRequired = (required_permission_level) => {
    return (req, res, next) => {
        let user_permission_level = parseInt(req.jwt.permissionLevel);
        let userId = req.jwt.userId;
        if (user_permission_level & required_permission_level) {
            return next();
        } else {
            return res.status(403).send();
        }
    };
};

if you want to check, say, minimumPermissionLevelRequired(PAID), where PAID=4, then a user with user_permission_level of 1 should not get access, but anyone with permissionLevel >= 4 (4, 8, ... 2048, eg) SHOULD get access.   But with that bitwise AND, only PAID users get access, not levels above that.  For admins, eg, 2048 & 4 returns 0, so admins do not get access (but they should).  That's why I wrote that I could only get it to work by doing an actual compare if (user_permission_level >= required_permission_level) { ... }   Anyway, I appreciate the response.  - Helen

**Comment by hht1230** [comment]
Ok, now I see. minimumPermission really means "as long as that bit is set" (not a value greater than the required_permission_level).  So a user with permissionLevel of 2052 (2048 bit and 4 bit) will have access.
